name: shounengaming_mangas_mobile
description: Shounen Gaming's Community App to Read Mangas.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  dio: ^5.1.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_carousel_slider: ^1.1.0
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  intl: ^0.18.1
  dash_flags: ^0.1.1
  visibility_detector: ^0.4.0+2
  photo_view: ^0.14.0
  flutter_expandable_fab: ^1.8.1
  focused_menu: ^1.0.5
  readmore: ^2.2.0
  jwt_decoder: ^2.0.1
  flutter_custom_tabs: ^1.0.4
  signalr_netcore: ^0.1.7+2-nullsafety.3
  scrollable_positioned_list: ^0.3.8
  fluttertoast: ^8.2.2
  toggle_switch: ^2.1.0
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-circle.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sources/
